# Generated by Django 4.0.6 on 2022-07-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='degree',
            field=models.CharField(blank=True, choices=[('Health Sciences', 'Health Sciences'), ('Engineering and IT', 'Engineering and IT'), ('Commerce', 'Commerce'), ('Design', 'Design')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='education_level',
            field=models.CharField(blank=True, choices=[('Undergraduate', 'Undergraduate'), ('Postgraduate', 'Postgraduate')], max_length=100, null=True),
        ),
    ]
