# Generated by Django 4.0.6 on 2022-07-20 02:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookloan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='borrow_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
