# Generated by Django 4.0.6 on 2022-07-22 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_book_is_available'),
        ('bookloan', '0003_alter_bookloan_borrow_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='book',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_available': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
    ]
