# Generated by Django 4.0.6 on 2022-07-20 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='issued_retured_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
