# Generated by Django 4.0.6 on 2022-07-20 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_book_borrow_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
